### ISSUE TITLE
请问sdk怎么下下来的？

### ISSUE THREAD

**Issue by JakeWoki** [thisfeng/EpsonPrinterSample#4]
[
ePOS_SDK_Android_v2.14.0.zip](http://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=6349&scat=61&pcat=52)
这个sdk死活下不下来，一直失败然后变成html，请问下作者怎么下下来的？这个demo的libs是哪个版本的？

**Comment by thisfeng** [comment]
demo中 ，请直接使用该项目中 libs 对应的 jar 文件 ，不需要去官网下载最新的

**Comment by thisfeng** [comment]
官网的下载话，试试翻墙下载，
此 demo中 ，对应的 libs 对应的 jar 文件 具体版本请查看  https://www.jianshu.com/p/178dcb046e56 内的截图

**Comment by thisfeng** [comment]
官网的下载话，试试翻墙下载，
此 demo中 ，对应的 libs 对应的 jar 文件 具体版本请查看 https://www.jianshu.com/p/178dcb046e56 内的截图 ，

**Comment by JakeWoki** [comment]
我叫他们技术下载发给我了，后来发现不支持那个打印机型号（WF-C5390a），但是又联系不是他们的技术了。。。

**Comment by thisfeng** [comment]
这个 Demo  我看只支持 爱普生的 TM_xxx 型号的， 我也接过 Star 的印机，Star也有专门的Sdk 供Android使用， 你应该找到你的印机对应的SDk文档进行阅读 。

**Comment by JakeWoki** [comment]
感谢！我去看看，喷墨式打印机提供sdk的不多
